### PR TITLE
Remove verbose logs from crypto_scalarmult

### PR DESCRIPTION
**Pull request by staltz**
This PR is a patch-1 because it's very simple.

### CODE REVIEW

**Comment by dominictarr** [comment]
thanks! sorry that was an embarrasing one

**Comment by dominictarr** [comment]
how did you spot this? is manyverse actually running this code? or did you see it in tests, or some other tool?

**Comment by dominictarr** [comment]
merged into 0.2.5

**Comment by staltz** [comment]
@dominictarr manyverse was actually running this code, constantly. I'll get a stack trace and study a bit why was that happening

**Pull request merged**
